const projectTypes = {
  GET_PROJECT_REQUEST: 'GET_PROJECT_REQUEST',
  GET_PROJECT_SUCCESS: 'GET_PROJECT_SUCCESS',
  GET_PROJECT_FAILURE: 'GET_PROJECT_FAILURE',

  GET_PROJECTS_REQUEST: 'GET_PROJECTS_REQUEST',
  GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
  GET_PROJECTS_FAILURE: 'GET_PROJECTS_FAILURE',

  GET_USER_PROJECTS_REQUEST: 'GET_USER_PROJECTS_REQUEST',
  GET_USER_PROJECTS_SUCCESS: 'GET_USER_PROJECTS_SUCCESS',
  GET_USER_PROJECTS_FAILURE: 'GET_USER_PROJECTS_FAILURE',

  GET_PARTICIPANT_PROJECTS_REQUEST: 'GET_PARTICIPANT_PROJECTS_REQUEST',
  GET_PARTICIPANT_PROJECTS_SUCCESS: 'GET_PARTICIPANT_PROJECTS_SUCCESS',
  GET_PARTICIPANT_PROJECTS_FAILURE: 'GET_PARTICIPANT_PROJECTS_FAILURE',

  CREATE_PROJECT_REQUEST: 'CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',

  EDIT_PROJECT_REQUEST: 'EDIT_PROJECT_REQUEST',
  EDIT_PROJECT_SUCCESS: 'EDIT_PROJECT_SUCCESS',
  EDIT_PROJECT_FAILURE: 'EDIT_PROJECT_FAILURE',

  ADD_CATEGORY_TO_PROJECT_REQUEST: 'ADD_CATEGORY_TO_PROJECT_REQUEST',
  ADD_CATEGORY_TO_PROJECT_SUCCESS: 'ADD_CATEGORY_TO_PROJECT_SUCCESS',
  ADD_CATEGORY_TO_PROJECT_FAILURE: 'ADD_CATEGORY_TO_PROJECT_FAILURE',

  DELETE_CATEGORY_FROM_PROJECT_REQUEST: 'DELETE_CATEGORY_FROM_PROJECT_REQUEST',
  DELETE_CATEGORY_FROM_PROJECT_SUCCESS: 'DELETE_CATEGORY_FROM_PROJECT_SUCCESS',
  DELETE_CATEGORY_FROM_PROJECT_FAILURE: 'DELETE_CATEGORY_FROM_PROJECT_FAILURE'
};

export default projectTypes;
