const taskTypes = {
  GET_TASK_REQUEST: 'GET_TASK_REQUEST',
  GET_TASK_SUCCESS: 'GET_TASK_SUCCESS',
  GET_TASK_FAILURE: 'GET_TASK_FAILURE',

  GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_FAILURE: 'GET_TASKS_FAILURE',

  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_FAILURE: 'CREATE_TASK_FAILURE',

  EDIT_TASK_REQUEST: 'EDIT_TASK_REQUEST',
  EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
  EDIT_TASK_FAILURE: 'EDIT_TASK_FAILURE',

  SET_TASK_EXECUTION_REQUEST: 'SET_TASK_EXECUTION_REQUEST',
  SET_TASK_EXECUTION_SUCCESS: 'SET_TASK_EXECUTION_SUCCESS',
  SET_TASK_EXECUTION_FAILURE: 'SET_TASK_EXECUTION_FAILURE',

  GET_ACTIVE_TASKS_REQUEST: 'GET_ACTIVE_TASKS_REQUEST',
  GET_ACTIVE_TASKS_SUCCESS: 'GET_ACTIVE_TASKS_SUCCESS',
  GET_ACTIVE_TASKS_FAILURE: 'GET_ACTIVE_TASKS_FAILURE',

  GET_OPENED_TASKS_REQUEST: 'GET_OPENED_TASKS_REQUEST',
  GET_OPENED_TASKS_SUCCESS: 'GET_OPENED_TASKS_SUCCESS',
  GET_OPENED_TASKS_FAILURE: 'GET_OPENED_TASKS_FAILURE',

  GET_CLOSED_TASKS_REQUEST: 'GET_CLOSED_TASKS_REQUEST',
  GET_CLOSED_TASKS_SUCCESS: 'GET_CLOSED_TASKS_SUCCESS',
  GET_CLOSED_TASKS_FAILURE: 'GET_CLOSED_TASKS_FAILURE',

  GET_PROJECT_TASKS_REQUEST: 'GET_PROJECT_TASKS_REQUEST',
  GET_PROJECT_TASKS_SUCCESS: 'GET_PROJECT_TASKS_SUCCESS',
  GET_PROJECT_TASKS_FAILURE: 'GET_PROJECT_TASKS_FAILURE'
};

export default taskTypes;
