const tokenTypes = {
  SELL_PROJECT_TOKENS_REQUEST: 'SELL_PROJECT_TOKENS_REQUEST',
  SELL_PROJECT_TOKENS_SUCCESS: 'SELL_PROJECT_TOKENS_SUCCESS',
  SELL_PROJECT_TOKENS_FAILURE: 'SELL_PROJECT_TOKENS_FAILURE',

  GET_PROJECT_TOKEN_OWNERS_REQUEST: 'GET_PROJECT_TOKEN_OWNERS_REQUEST',
  GET_PROJECT_TOKEN_OWNERS_SUCCESS: 'GET_PROJECT_TOKEN_OWNERS_SUCCESS',
  GET_PROJECT_TOKEN_OWNERS_FAILURE: 'GET_PROJECT_TOKEN_OWNERS_FAILURE',

  GET_PROJECT_TOKEN_SALARY_REQUEST: 'GET_PROJECT_TOKEN_SALARY_REQUEST',
  GET_PROJECT_TOKEN_SALARY_SUCCESS: 'GET_PROJECT_TOKEN_SALARY_SUCCESS',
  GET_PROJECT_TOKEN_SALARY_FAILURE: 'GET_PROJECT_TOKEN_SALARY_FAILURE',

  SET_PROJECT_TOKEN_PRICE_REQUEST: 'SET_PROJECT_TOKEN_PRICE_REQUEST',
  SET_PROJECT_TOKEN_PRICE_SUCCESS: 'SET_PROJECT_TOKEN_PRICE_SUCCESS',
  SET_PROJECT_TOKEN_PRICE_FAILURE: 'SET_PROJECT_TOKEN_PRICE_FAILURE',

  BACK_SELL_PROJECT_TOKENS_REQUEST: 'BACK_SELL_PROJECT_TOKENS_REQUEST',
  BACK_SELL_PROJECT_TOKENS_SUCCESS: 'BACK_SELL_PROJECT_TOKENS_SUCCESS',
  BACK_SELL_PROJECT_TOKENS_FAILURE: 'BACK_SELL_PROJECT_TOKENS_FAILURE',

  BUY_TOKEN_REQUEST: 'BUY_TOKEN_REQUEST',
  BUY_TOKEN_SUCCESS: 'BUY_TOKEN_SUCCESS',
  BUY_TOKEN_FAILURE: 'BUY_TOKEN_FAILURE',

  GET_TOKEN_TRADING_REQUEST: 'GET_TOKEN_TRADING_REQUEST',
  GET_TOKEN_TRADING_SUCCESS: 'GET_TOKEN_TRADING_SUCCESS',
  GET_TOKEN_TRADING_FAILURE: 'GET_TOKEN_TRADING_FAILURE',

  GET_USER_TOKENS_REQUEST: 'GET_USER_TOKENS_REQUEST',
  GET_USER_TOKENS_SUCCESS: 'GET_USER_TOKENS_SUCCESS',
  GET_USER_TOKENS_FAILURE: 'GET_USER_TOKENS_FAILURE'
};

export default tokenTypes;
