const userTypes = {
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  GET_INFO_ABOUT_ME_REQUEST: 'GET_INFO_ABOUT_ME_REQUEST',
  GET_INFO_ABOUT_ME_SUCCESS: 'GET_INFO_ABOUT_ME_SUCCESS',
  GET_INFO_ABOUT_ME_FAILURE: 'GET_INFO_ABOUT_ME_FAILURE',

  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',

  GET_USER_COMMENTS_REQUEST: 'GET_USER_COMMENTS_REQUEST',
  GET_USER_COMMENTS_SUCCESS: 'GET_USER_COMMENTS_SUCCESS',
  GET_USER_COMMENTS_FAILURE: 'GET_USER_COMMENTS_FAILURE',

  ADD_USER_LANGUAGE_REQUEST: 'ADD_USER_LANGUAGE_REQUEST',
  ADD_USER_LANGUAGE_SUCCESS: 'ADD_USER_LANGUAGE_SUCCESS',
  ADD_USER_LANGUAGE_FAILURE: 'ADD_USER_LANGUAGE_FAILURE',

  DELETE_USER_LANGUAGE_REQUEST: 'DELETE_USER_LANGUAGE_REQUEST',
  DELETE_USER_LANGUAGE_SUCCESS: 'DELETE_USER_LANGUAGE_SUCCESS',
  DELETE_USER_LANGUAGE_FAILURE: 'DELETE_USER_LANGUAGE_FAILURE',

  ADD_USER_EDUCATION_REQUEST: 'ADD_USER_EDUCATION_REQUEST',
  ADD_USER_EDUCATION_SUCCESS: 'ADD_USER_EDUCATION_SUCCESS',
  ADD_USER_EDUCATION_FAILURE: 'ADD_USER_EDUCATION_FAILURE',

  DELETE_USER_EDUCATION_REQUEST: 'DELETE_USER_EDUCATION_REQUEST',
  DELETE_USER_EDUCATION_SUCCESS: 'DELETE_USER_EDUCATION_SUCCESS',
  DELETE_USER_EDUCATION_FAILURE: 'DELETE_USER_EDUCATION_FAILURE',

  ADD_USER_SKILL_REQUEST: 'ADD_USER_SKILL_REQUEST',
  ADD_USER_SKILL_SUCCESS: 'ADD_USER_SKILL_SUCCESS',
  ADD_USER_SKILL_FAILURE: 'ADD_USER_SKILL_FAILURE',

  DELETE_USER_SKILL_REQUEST: 'DELETE_USER_SKILL_REQUEST',
  DELETE_USER_SKILL_SUCCESS: 'DELETE_USER_SKILL_SUCCESS',
  DELETE_USER_SKILL_FAILURE: 'DELETE_USER_SKILL_FAILURE',

  ADD_USER_WORK_EXPERIENCE_REQUEST: 'ADD_USER_WORK_EXPERIENCE_REQUEST',
  ADD_USER_WORK_EXPERIENCE_SUCCESS: 'ADD_USER_WORK_EXPERIENCE_SUCCESS',
  ADD_USER_WORK_EXPERIENCE_FAILURE: 'ADD_USER_WORK_EXPERIENCE_FAILURE',

  DELETE_USER_WORK_EXPERIENCE_REQUEST: 'DELETE_USER_WORK_EXPERIENCE_REQUEST',
  DELETE_USER_WORK_EXPERIENCE_SUCCESS: 'DELETE_USER_WORK_EXPERIENCE_SUCCESS',
  DELETE_USER_WORK_EXPERIENCE_FAILURE: 'DELETE_USER_WORK_EXPERIENCE_FAILURE'
};

export default userTypes;
